IBM/platform-services-go-sdk

casemanagementv1/case_management_v1_integration_test.go

**Fixes:** <! -- link to issue -->

Added integration tests to Case Management SDK

---

README.md
configurationgovernancev1/configuration_governance_v1.go
configurationgovernancev1/configuration_governance_v1_examples_test.go
configurationgovernancev1/configuration_governance_v1_integration_test.go
configurationgovernancev1/configuration_governance_v1_suite_test.go
configurationgovernancev1/configuration_governance_v1_test.go
go.mod
go.sum

This PR adds the Configuration Governance service to the project.

feat(Configuration Governance): add service to project

---

atrackerv1/atracker_v1.go
atrackerv1/atracker_v1_examples_test.go
atrackerv1/atracker_v1_integration_test.go
atrackerv1/atracker_v1_test.go

This PR contains an update to the Activity Tracker service after [recent](https://github.ibm.com/mkistler/atracker/commit/cbbea2738b78e0d8a0bb72f975305e3bbb6dbceb) API changes.

fix(Activity Tracker): re-gen service after recent API changes

---

atrackerv1/atracker_v1_examples_test.go
casemanagementv1/case_management_v1_examples_test.go
configurationgovernancev1/configuration_governance_v1_examples_test.go
enterprisebillingunitsv1/enterprise_billing_units_v1_examples_test.go
enterpriseusagereportsv1/enterprise_usage_reports_v1_examples_test.go
globalcatalogv1/global_catalog_v1_examples_test.go
globalsearchv2/global_search_v2_examples_test.go
globaltaggingv1/global_tagging_v1_examples_test.go
iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
iamidentityv1/iam_identity_v1_examples_test.go
iampolicymanagementv1/iam_policy_management_v1_examples_test.go
openservicebrokerv1/open_service_broker_v1_examples_test.go
resourcecontrollerv2/resource_controller_v2_examples_test.go
resourcemanagerv2/resource_manager_v2_examples_test.go
usagemeteringv4/usage_metering_v4_examples_test.go
usagereportsv4/usage_reports_v4_examples_test.go
usermanagementv1/user_management_v1_examples_test.go

This PR adds labels to example output, so that it is easier to identify which section of the output belongs to which method.

fix: add labels to examples

---

.secrets.baseline
README.md
go.sum
posturemanagementv1/posture_management_v1.go
posturemanagementv1/posture_management_v1_examples_test.go
posturemanagementv1/posture_management_v1_integration_test.go
posturemanagementv1/posture_management_v1_suite_test.go
posturemanagementv1/posture_management_v1_test.go

This PR adds the Posture Management service to the project.

feat(Posture Management): add service to project

---

resourcecontrollerv2/resource_controller_v2_examples_test.go

This PR modifies the Resource Controller working examples so that the labels displayed in the output will not be included in the API reference.

chore: hide labels from API reference

---

go.mod
go.sum
openservicebrokerv1/open_service_broker_v1_integration_test.go
resourcecontrollerv2/resource_controller_v2_integration_test.go

This PR contains changes to avoid the use of the github.com/satori/go.uuid dependency because it has been found to contain a vulnerability: https://snyk.io/vuln/SNYK-GOLANG-GITHUBCOMSATORIGOUUID-72488?utm_medium=Partner&utm_source=IBM-Cloud&utm_campaign=DevOps-Code-Risk-Analyzer-Integrates-Snyk-Intel
Instead, the code now uses the github.com/google/uuid package.

fix: avoid satori/go.uuid dep due to vulnerability

---

atrackerv1/atracker_v1.go
atrackerv1/atracker_v1_test.go

fix(Activity Tracker): re-gen service after recent service name change

---

Makefile
go.mod
go.sum

This PR bumps the version of go core to 5.6.3 to pull in the new ContainerAuthenticator functionality.

fix: bump go core version to 5.6.3

---

iamidentityv1/iam_identity_v1.go
iamidentityv1/iam_identity_v1_examples_test.go
iamidentityv1/iam_identity_v1_integration_test.go
iamidentityv1/iam_identity_v1_test.go

This pr contains all the supported endpoints of Iam-Identity's trusted profiles.
we recently went public and here is the documentation: https://test.cloud.ibm.com/apidocs/iam-identity-token-api

feat(iam-identity): adding trusted profiles

---

contextbasedrestrictionsv1/context_based_restrictions_v1.go
contextbasedrestrictionsv1/context_based_restrictions_v1_integration_test.go
contextbasedrestrictionsv1/context_based_restrictions_v1_test.go

Added support for the `X-Correlation-Id` header
- Added support for passing the standard `X-Correlation-Id` header in each request
- Updated some swagger properties summaries and descriptions
This enhancement adds support for passing the standard `X-Correlation-Id` header in each request. This is an optional header and it does not break backward compatibility.

feat(Context based Restrictions): add support for the X-Correlation-Id header

---

iamaccessgroupsv2/iam_access_groups_v2.go
iamaccessgroupsv2/iam_access_groups_v2_suite_test.go
iamaccessgroupsv2/iam_access_groups_v2_test.go

Updated documentation and examples by added a new member type trusted profile.

fix(IAM Access Groups): add trusted profile as member

---

iamidentityv1/iam_identity_v1.go
iamidentityv1/iam_identity_v1_examples_test.go
iamidentityv1/iam_identity_v1_integration_test.go
iamidentityv1/iam_identity_v1_suite_test.go
iamidentityv1/iam_identity_v1_test.go

adding new endpoints: create report, get report
adding new optional query parameter include_activity for the existing get calls of apikey/serviceid/profile by id.
users will now be able to generate report for inactive identities.
create report: will return a reference
get report: this will return a detailed report of inactive identities
existing get apikey/serviceid/profile by id will now include additional optional parameter include_activity
if include_activity is passed as true the response will include a new section activity with last authn time and count.

feat(IAM Identity): add support for inactivity reports

---

resourcecontrollerv2/resource_controller_v2.go
resourcecontrollerv2/resource_controller_v2_examples_test.go
resourcecontrollerv2/resource_controller_v2_integration_test.go
resourcecontrollerv2/resource_controller_v2_test.go

Signed-off-by: apoorva9s14 <apoorvalaiti16@gmail.com>
For the resource controller service update as per this PR - https://github.ibm.com/cloud-api-docs/resource-controller/pull/244, resource-controller-v2.yaml is the updated yaml, I have regenerated the SDK files with openapi-sdkgen.
We are looking to address:
Looping - https://github.ibm.com/cloud-api-docs/resource-controller/issues/226
Credentials redaction
- [ Yes] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ Yes] Docs have been added / updated (for bug fixes / features)
The examples and the SDK code snippet in the apidocs would be updated for …

ResourceController service update

---

atrackerv1/atracker_v1_test.go
atrackerv2/atracker_v2_test.go
casemanagementv1/case_management_v1_examples_test.go
casemanagementv1/case_management_v1_integration_test.go
casemanagementv1/case_management_v1_test.go
catalogmanagementv1/catalog_management_v1_test.go
configurationgovernancev1/configuration_governance_v1_test.go
contextbasedrestrictionsv1/context_based_restrictions_v1_test.go
enterprisebillingunitsv1/enterprise_billing_units_v1_test.go
enterprisemanagementv1/enterprise_management_v1_test.go
enterpriseusagereportsv1/enterprise_usage_reports_v1_test.go
globalcatalogv1/global_catalog_v1_examples_test.go
globalcatalogv1/global_catalog_v1_integration_test.go
globalcatalogv1/global_catalog_v1_test.go
globalsearchv2/global_search_v2_test.go
globaltaggingv1/global_tagging_v1_test.go
iamaccessgroupsv2/iam_access_groups_v2_test.go
iamidentityv1/iam_identity_v1_test.go
iampolicymanagementv1/iam_policy_management_v1_test.go
ibmcloudshellv1/ibm_cloud_shell_v1_test.go
openservicebrokerv1/open_service_broker_v1_test.go
posturemanagementv1/posture_management_v1_test.go
resourcecontrollerv2/resource_controller_v2_test.go
resourcemanagerv2/resource_manager_v2_test.go
usagemeteringv4/usage_metering_v4_test.go
usagereportsv4/usage_reports_v4_test.go
usermanagementv1/user_management_v1_test.go

This commit replaces the `ioutil` package with `io` and `os`,
because it's became deprecated in Go 1.16. As of the release
of Go 1.19, our linter started to throw errors due to this old imports.
Signed-off-by: Norbert Biczo <pyrooka@users.noreply.github.com>

chore: replace `ioutil` with `io` and `os`

---

atrackerv2/atracker_v2.go
atrackerv2/atracker_v2_integration_test.go
atrackerv2/atracker_v2_test.go

Signed-off-by: Veena Rao <veenar@us.ibm.com>

fix(Activity Tracker): Added support for event streams targets in Atracker v2 API

---

atrackerv1/atracker_v1.go
atrackerv1/atracker_v1_test.go
atrackerv2/atracker_v2.go
atrackerv2/atracker_v2_test.go

Atracker Changes version 1 and 2: Adds in service regions remapped for the following:
| provider region | ATracker region |
|----------------|-----------------|
| ca-tor | us-east |
| br-sao | us-south |
| eu-fr2 | eu-de |
| jp-tok | eu-de |
| jp-osa | eu-de |
| in-che | eu-de |

fix(Activity Tracker): adds remapping to other regions

---

.secrets.baseline
enterpriseusagereportsv1/enterprise_usage_reports_v1.go
enterpriseusagereportsv1/enterprise_usage_reports_v1_examples_test.go
enterpriseusagereportsv1/enterprise_usage_reports_v1_integration_test.go
enterpriseusagereportsv1/enterprise_usage_reports_v1_suite_test.go
enterpriseusagereportsv1/enterprise_usage_reports_v1_test.go

This commit contains a re-gen of the service to
leverage the new Pagers emitted by the SDK generator.

fix(Enterprise Usage Reports): regen service to get Pager

---

iampolicymanagementv1/iam_policy_management_v1.go
iampolicymanagementv1/iam_policy_management_v1_examples_test.go
iampolicymanagementv1/iam_policy_management_v1_integration_test.go
iampolicymanagementv1/iam_policy_management_v1_suite_test.go
iampolicymanagementv1/iam_policy_management_v1_test.go

Code to support new v2/policies API has been introduced. The new v2/policies API will have new JSON fields and existing v1/fields have been changed.
v1/policies API will continue to be supported.
PR's are currently open for staging and production docs. They are not currently merged:
Staging: https://github.ibm.com/cloud-api-docs/iam-access-management/pull/139
Production: https://github.ibm.com/cloud-api-docs/iam-access-management/pull/140
Current behavior will remain same (v1 will continue to be supported). New behavior is v2/policies support which allows for time based restriction policies using new rule field (an integration test has been added of this example).
See:
Issue: …

feat(IAM Policy Management): add support for v2/policies API from IAM

---

usagereportsv4/usage_reports_v4.go
usagereportsv4/usage_reports_v4_suite_test.go
usagereportsv4/usage_reports_v4_test.go

Rename the `billing_month` property in the `Account_Summary` schema to `month`
The `Account_Summary` schema should now have the `month` property instead of the `billing_month` property.

fix: rename Account_Summary billing_month property

---

iampolicymanagementv1/iam_policy_management_v1.go
iampolicymanagementv1/iam_policy_management_v1_examples_test.go
iampolicymanagementv1/iam_policy_management_v1_integration_test.go
iampolicymanagementv1/iam_policy_management_v1_test.go

V2Roles to support optional query parameter service_group_id
Fixed replacePolicy example
PR's are merged:
Staging: https://github.ibm.com/cloud-api-docs/iam-access-management/pull/162
Production: https://github.ibm.com/cloud-api-docs/iam-access-management/pull/163
https://github.ibm.com/IAM/AM-issues/issues/645

feat(IAM Policy Management): support of new query param source_group_id for v2/roles

---

globalsearchv2/global_search_v2.go
globalsearchv2/global_search_v2_examples_test.go
globalsearchv2/global_search_v2_integration_test.go
globalsearchv2/global_search_v2_test.go

Removed references to /v2/resources/supported_types

fix(Global Search): remove deprecated method getSupportedTypes

---

usermanagementv1/user_management_v1.go
usermanagementv1/user_management_v1_examples_test.go
usermanagementv1/user_management_v1_integration_test.go
usermanagementv1/user_management_v1_suite_test.go
usermanagementv1/user_management_v1_test.go

Update Include_settings and substring search functionality (User Management) 
the current issue for updating SDK https://github.ibm.com/IAM/uum/issues/5882 
the previous issue for the user management code change https://github.ibm.com/IAM/uum/issues/4948

feat (User Management): add query params search and include_settings to list_users operation

---

iamidentityv1/iam_identity_v1.go
iamidentityv1/iam_identity_v1_examples_test.go
iamidentityv1/iam_identity_v1_integration_test.go
iamidentityv1/iam_identity_v1_test.go

Added support for IAM enterprise feature. Enterprise admins can create templates for account settings and trusted profiles and assign them to accounts and account groups in the enterprise.
SDK adopters will be able to work with IAM enterprise feature.
API definition: [Staging](https://test.cloud.ibm.com/apidocs/iam-identity-token-api#list-profile-templates)
Test information:
Integration Tests:
```
Ran 490 of 490 Specs in 814.586 seconds
SUCCESS! -- 490 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/iamidentityv1   817.700s
```
Examples:
```
Ran 473 of 473 Specs in 759.903 seconds
SUCCESS! -- 473 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok …
```

feat(IAM Identity): Add support for IAM enterprise

---

Makefile

This PR simply adds the `--timeout 120s` option to the linter command in Makefile.

build: increase timeout for linter

---

CONTRIBUTING.md
Makefile
go.mod
go.sum
update_service.md

This PR updates the project to allow builds to be done on Windows.

fix: enable builds on windows

---

contextbasedrestrictionsv1/context_based_restrictions_v1.go
contextbasedrestrictionsv1/context_based_restrictions_v1_examples_test.go
contextbasedrestrictionsv1/context_based_restrictions_v1_integration_test.go
contextbasedrestrictionsv1/context_based_restrictions_v1_suite_test.go
contextbasedrestrictionsv1/context_based_restrictions_v1_test.go

Adds service group support to operations
service_name parameter can now be replaced with the service group parameter.

feat(Context-Based Restrictions): add service group support to Operations

---

CHANGELOG.md
contextbasedrestrictionsv1/context_based_restrictions_v1.go
contextbasedrestrictionsv1/context_based_restrictions_v1_integration_test.go
contextbasedrestrictionsv1/context_based_restrictions_v1_test.go

Add on to previous work:
https://github.com/IBM/platform-services-go-sdk/pull/277
The output is improper due to generation from an older version of the swagger. The change should be very minor and will be propagated to the other languages' PRs.
Adds the "Type" output

 fix(Context-Based Restrictions): fix output to Operations

---

iampolicymanagementv1/iam_policy_management_v1.go
iampolicymanagementv1/iam_policy_management_v1_examples_test.go
iampolicymanagementv1/iam_policy_management_v1_integration_test.go
iampolicymanagementv1/iam_policy_management_v1_test.go

Updated based on API definition fix to allow for `conditions` under `rule.conditions`.
Tests:
Examples:
```sh
go test -tags=examples
Ran 213 of 213 Specs in 13.890 seconds
SUCCESS! -- 213 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/iampolicymanagementv1	14.331s
```
Integration:
```sh
go test -tags=integration
Ran 211 of 211 Specs in 21.518 seconds
SUCCESS! -- 211 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/iampolicymanagementv1	22.384s
```
Updates Rule to allow for properties that are already allowed for in API.
issue: https://github.ibm.com/IAM/AM-issues/issues/1908

fix(IAM Policy Management): Added nest conditions to rule.conditions

---

iampolicymanagementv1/iam_policy_management_v1_examples_test.go

Issue: https://github.ibm.com/IAM/AM-issues/issues/2001
Updating examples so that the API doc generation includes the etag response header.
No behavior change.
Ran examples to verify changes:
```sh
go test -tags=examples
Running Suite: IamPolicyManagementV1 Suite
==========================================
Random Seed: 1706561751
Will run 214 of 214 specs
...
Ran 214 of 214 Specs in 13.503 seconds
SUCCESS! -- 214 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
```

fix(IAM Policy Management): update examples format for doc generation

---

iampolicymanagementv1/iam_policy_management_v1.go
iampolicymanagementv1/iam_policy_management_v1_test.go

This is a minor regeneration based on update to enum for operators in v2/policies.
Issue: https://github.ibm.com/IAM/AM-issues/issues/2212
Tests:
```sh
go test -tags=examples
...
Ran 214 of 214 Specs in 19.609 seconds
SUCCESS! -- 214 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/iampolicymanagementv1	20.361s
```
```sh
go test -tags=integration
...
Ran 212 of 212 Specs in 16.369 seconds
SUCCESS! -- 212 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
```

fix(IAM Policy Management): regenerate based on minor API update to operator enum

---

contextbasedrestrictionsv1/context_based_restrictions_v1.go
contextbasedrestrictionsv1/context_based_restrictions_v1_examples_test.go
contextbasedrestrictionsv1/context_based_restrictions_v1_integration_test.go
contextbasedrestrictionsv1/context_based_restrictions_v1_suite_test.go
contextbasedrestrictionsv1/context_based_restrictions_v1_test.go

Add support for new endpoint
Update examples to match the API
Adds new endpoint for singular service ref target

feat(Context-Based Restrictions): add Service Ref Target

---

metricsrouterv3/metrics_router_v3.go
metricsrouterv3/metrics_router_v3_test.go

Added new regions Sao Paulo(br-sao), Toronto(ca-tor), Osaka(jp-tok) and Tokyo(jp-tok) to metrics-router
Added new region. No change in old code

fix(Metrics Router): add new regions br-sao, ca-tor, jp-osa and jp-tok

---

atrackerv2/atracker_v2.go
atrackerv2/atracker_v2_test.go

Added new regions Sao Paulo(br-sao), Toronto(ca-tor), Osaka(jp-tok), Tokyo(jp-tok) and Chennai(in-che) to ATracker
Added new region. No change in old code

fix(ATracker): add new regions br-sao, ca-tor, jp-osa, jp-tok and in-che

---

atrackerv2/atracker_v2.go
atrackerv2/atracker_v2_examples_test.go
atrackerv2/atracker_v2_integration_test.go
atrackerv2/atracker_v2_test.go

Add support for a new ATracker target type (cloud-logs) and its endpoint fields
ATracker will support a new target type (cloud-logs) in addition to the existing target types
Unit tests results:
```
veenarao$ go test
go: downloading github.com/onsi/gomega v1.31.1
Running Suite: AtrackerV2 Suite
===============================
Random Seed: 1712004023
Will run 94 of 94 specs
••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 94 of 94 Specs in 4.006 seconds
SUCCESS! -- 94 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/atrackerv2	5.064s
```
Integration test results:
```
veenarao$ go test …
```

fix (ATracker): add support for Cloud Logs target type

---

enterprisemanagementv1/enterprise_management_v1.go
enterprisemanagementv1/enterprise_management_v1_test.go

Re-Generated the SDK using correct steps

fix(Enterprise Management): re-gen service with latest API definition

---

usagereportsv4/usage_reports_v4.go
usagereportsv4/usage_reports_v4_test.go

re-add the offset property to SnapshotListNext which was incorrectly removed after re-generating the service
SnapshotListNext should now contain the offset property
test results:
```
Running Suite: UsageReportsV4 Suite
===================================
Random Seed: 1714067348
Will run 103 of 103 specs
•••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••
Ran 103 of 103 Specs in 3.204 seconds
SUCCESS! -- 103 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok      github.com/IBM/platform-services-go-sdk/usagereportsv4  3.852s
```
integration tests:
```
Running Suite: UsageReportsV4 Suite
===================================
Random Seed: 1714067407
Will run 119 of 119 specs …
```

fix(Usage Reports): re-add offset to SnapshotListNext

---

.golangci.yaml
.secrets.baseline
.travis.yml
Makefile

This commit removes the use of the gosec standalone tool and enables the gosec linter supported by golangci-lint.

build: enable gosec linter in golangci-lint

---

ibmcloudshellv1/ibm_cloud_shell_v1.go
ibmcloudshellv1/ibm_cloud_shell_v1_examples_test.go
ibmcloudshellv1/ibm_cloud_shell_v1_integration_test.go
ibmcloudshellv1/ibm_cloud_shell_v1_suite_test.go
ibmcloudshellv1/ibm_cloud_shell_v1_test.go

feat(IBM Cloud Shell): re-gen service to adopt the new error toolchain

---

iamidentityv1/iam_identity_v1.go
iamidentityv1/iam_identity_v1_examples_test.go
iamidentityv1/iam_identity_v1_integration_test.go
iamidentityv1/iam_identity_v1_suite_test.go
iamidentityv1/iam_identity_v1_test.go

feat(IAM Identity): add Identity Preference API

---

atrackerv2/atracker_v2.go
atrackerv2/atracker_v2_integration_test.go
atrackerv2/atracker_v2_suite_test.go
atrackerv2/atracker_v2_test.go

- Due to Mezmo (LogDNA) end of service after 3/30/2025, remove logdna related reference from atracker sdk.
This PR removes `logdna` support because logdna (mezmo) will be end of service after 3/30. No changes to API itself, but customers will not be able to create/update any targets in `logdna` type. This has been communicated to customers.

fix(Atracker): re-gen service for mezmo removal and hand edits IT
