- .gitignore
- .travis.yml
- global_catalog.env.enc
- globalcatalogv1/global_catalog_v1_integration_test.go
Includes integration tests for Global Catalog SDK.
> test: add global catalog integration tests

- iamaccessgroupsv2/iam_access_groups_v2_integration_test.go
Additional changes that reduce the chance of test failures caused by parallel test runs.
- User ids are now unique
- Only old tests that failed to clean up or the current test group are cleaned up.
**Fixes:** https://github.ibm.com/IAM/uum/issues/2348
Integration tests have chances of intermittent failures.
Intermittent failures of integration tests are less likely/fixed.
> test(IAM Access Groups): Additional fixes to reduce integration test failures

- resourcemanagerv2/resource_manager_v2_integration_test.go
**Fixes:** <! -- link to issue -->
> test: add integration tests for resource manager service

- .travis.yml
This PR disables integration tests within tagged-release builds.
> fix(build): disable integration tests in tagged-release builds

- enterprisemanagementv1/enterprise_management_v1_integration_test.go
This PR fixes a problem in the EnterpriseManagement integration test.
> test: use correct date format with account helper operations

- .travis.yml
- Makefile
- go.mod
- go.sum
This PR simplifies the build process a bit by introducing a Makefile to run the various commands.
The PR also upgrades the go core to the latest available.
> chore: use make to run build commands

- .travis.yml
This PR temporarily disables the integration tests for both Enterprise Mgmt and Resource Mgr
due to the repeated failures.
> build: disable int tests for EM and RM

- globalcatalogv1/global_catalog_v1.go
- globalcatalogv1/global_catalog_v1_integration_test.go
- globalcatalogv1/global_catalog_v1_test.go
This PR contains a re-gen of the Global Catalog service due to recent changes in the API definition, along with a minor change to the integration test to accomodate it.
> fix(Global Catalog): regen code from new API definition

- iampolicymanagementv1/iam_policy_management_v1_integration_test.go
> Add integration tests for policy mgmt service

- .travis.yml
- Makefile
This PR disables the Case Management integration test until it can be properly diagnosed and fixed.
This is being done so that clean master-branch builds can occur again.
> chore: disable case-mgmt test until it can be fixed

- catalogmanagementv1/catalog_management_v1_integration_test.go
> test: more test hardening for cm integration tests

- casemanagementv1/case_management_v1_test.go
- enterprisemanagementv1/enterprise_management_v1_test.go
- globalcatalogv1/global_catalog_v1_test.go
- globalsearchv2/global_search_v2.go
- globalsearchv2/global_search_v2_test.go
- globaltaggingv1/global_tagging_v1.go
- globaltaggingv1/global_tagging_v1_test.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
- resourcemanagerv2/resource_manager_v2_test.go
This PR contains updates to generated code.
> Regenerate service/test code using the latest API definitions

- iampolicymanagementv1/iam_policy_management_v1_integration_test.go
Re-enable IAM Policy Management test methods that were temporarily skipped.
> test: re-enable skipped ipm test methods

- .travis.yml
- catalogmanagementv1/catalog_management_v1_integration_test.go
Disables integration tests in travis builds due to lack of reliability.
> test: bypass integration tests in travis builds

- catalogmanagementv1/catalog_management_v1_integration_test.go
- go.mod
- go.sum
Upgrades go core dependency.
Fixes a minor problem in the cat-mgmt integration test.
> Fix cat mgmt integration test

- README.md
- usermanagementv1/user_management_v1.go
- usermanagementv1/user_management_v1_integration_test.go
- usermanagementv1/user_management_v1_suite_test.go
- usermanagementv1/user_management_v1_test.go
This PR adds the User Management service to the project/
> feat(User Management): add service to project

- usermanagementv1/user_management_v1.go
- usermanagementv1/user_management_v1_test.go
This PR contains a regen of the User Management service.
> fix(User Management): re-gen user-mgmt service

- go.mod
- go.sum
This PR upgrades the Go core version to 4.5.0
> chore: upgrade go core to 4.5.0

- README.md
- iamidentityv1/iam_identity_v1.go
- iamidentityv1/iam_identity_v1_examples_test.go
- iamidentityv1/iam_identity_v1_integration_test.go
- iamidentityv1/iam_identity_v1_suite_test.go
- iamidentityv1/iam_identity_v1_test.go
This PR adds the IAM Identity service to the project.
> feat(IAM Identity): add service to project

- README.md
- usagereportsv4/usage_reports_v4.go
- usagereportsv4/usage_reports_v4_examples_test.go
- usagereportsv4/usage_reports_v4_integration_test.go
- usagereportsv4/usage_reports_v4_suite_test.go
- usagereportsv4/usage_reports_v4_test.go
This PR adds the Usage Reports service to the project.
> feat(Usage Reports): add service to project

- README.md
- enterpriseusagereportsv1/enterprise_usage_reports_v1.go
- enterpriseusagereportsv1/enterprise_usage_reports_v1_examples_test.go
- enterpriseusagereportsv1/enterprise_usage_reports_v1_integration_test.go
- enterpriseusagereportsv1/enterprise_usage_reports_v1_suite_test.go
- enterpriseusagereportsv1/enterprise_usage_reports_v1_test.go
This PR adds the Enterprise Usage Reports service to the project, including examples and integration tests.
> feat(Enterprise Usage Reports): add service to project

- configurationgovernancev1/configuration_governance_v1.go
- configurationgovernancev1/configuration_governance_v1_examples_test.go
- configurationgovernancev1/configuration_governance_v1_integration_test.go
- configurationgovernancev1/configuration_governance_v1_test.go
Re-gen of Configuration Governance service, plus updates to int test and examples.
> fix(Configuration Governance): update service with recent API changes

- casemanagementv1/case_management_v1_integration_test.go
- iamidentityv1/iam_identity_v1.go
- iamidentityv1/iam_identity_v1_test.go
This PR includes a re-gen of IAM Identity after recent changes to the API.
> Datetime updates

- atrackerv1/atracker_v1_examples_test.go
- atrackerv1/atracker_v1_integration_test.go
**Fixes:** <! -- link to issue -->
> chore: update atracker service integration and example tests

- atrackerv1/atracker_v1.go
- atrackerv1/atracker_v1_test.go
Re-gen of Activity Tracker service after recent API changes.
> fix(Activity Tracker): re-gen after recent API changes

- usermanagementv1/user_management_v1.go
- usermanagementv1/user_management_v1_integration_test.go
- usermanagementv1/user_management_v1_test.go
This PR contains a re-gen of the User Management service plus updates to the integration tests after recent API changes.
> fix(User Management): re-gen service and update tests after API changes

- atrackerv1/atracker_v1.go
- atrackerv1/atracker_v1_examples_test.go
- atrackerv1/atracker_v1_integration_test.go
- atrackerv1/atracker_v1_test.go
This PR contains an update to the Activity Tracker service after recent API changes.
> fix(Activity Tracker): regen service after recent API changes

- README.md
- enterprisebillingunitsv1/enterprise_billing_units_v1.go
- enterprisebillingunitsv1/enterprise_billing_units_v1_examples_test.go
- enterprisebillingunitsv1/enterprise_billing_units_v1_integration_test.go
- enterprisebillingunitsv1/enterprise_billing_units_v1_suite_test.go
- enterprisebillingunitsv1/enterprise_billing_units_v1_test.go
This PR adds the Enterprise Billing Units service to the project
> feat(Enterprise Billing Units): add service to project

- README.md
- go.mod
- go.sum
- usagemeteringv4/usage_metering_v4.go
- usagemeteringv4/usage_metering_v4_examples_test.go
- usagemeteringv4/usage_metering_v4_integration_test.go
- usagemeteringv4/usage_metering_v4_suite_test.go
- usagemeteringv4/usage_metering_v4_test.go
This PR adds the Usage Metering service to the project.
> feat(Usage Metering): add service to project

- atrackerv1/atracker_v1.go
- atrackerv1/atracker_v1_examples_test.go
- atrackerv1/atracker_v1_integration_test.go
- atrackerv1/atracker_v1_test.go
- casemanagementv1/case_management_v1.go
- casemanagementv1/case_management_v1_integration_test.go
- casemanagementv1/case_management_v1_test.go
- configurationgovernancev1/configuration_governance_v1.go
- configurationgovernancev1/configuration_governance_v1_test.go
- enterprisebillingunitsv1/enterprise_billing_units_v1.go
- enterprisebillingunitsv1/enterprise_billing_units_v1_test.go
- enterprisemanagementv1/enterprise_management_v1.go
- enterprisemanagementv1/enterprise_management_v1_integration_test.go
- enterprisemanagementv1/enterprise_management_v1_test.go
- enterpriseusagereportsv1/enterprise_usage_reports_v1.go
- enterpriseusagereportsv1/enterprise_usage_reports_v1_test.go
- globalcatalogv1/global_catalog_v1.go
- globalcatalogv1/global_catalog_v1_test.go
- globalsearchv2/global_search_v2.go
- globalsearchv2/global_search_v2_examples_test.go
- globalsearchv2/global_search_v2_integration_test.go
- globalsearchv2/global_search_v2_test.go
- globaltaggingv1/global_tagging_v1.go
- globaltaggingv1/global_tagging_v1_test.go
This PR updates several services with improved name formatting enabled and adds examples for the Global Search service.
> re-gen services and add examples

- iamaccessgroupsv2/iam_access_groups_v2.go
- iamaccessgroupsv2/iam_access_groups_v2_suite_test.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
Re-gen of IAM Access Groups service...
> fix(IAM Access Groups): minor code re-gen after recent API changes

- configurationgovernancev1/configuration_governance_v1.go
- configurationgovernancev1/configuration_governance_v1_examples_test.go
- configurationgovernancev1/configuration_governance_v1_integration_test.go
- configurationgovernancev1/configuration_governance_v1_suite_test.go
- configurationgovernancev1/configuration_governance_v1_test.go
**Fixes:** <! -- link to issue -->
> fix(Configuration Governance): re-gen service after recent API changes

- globaltaggingv1/global_tagging_v1.go
- globaltaggingv1/global_tagging_v1_examples_test.go
- globaltaggingv1/global_tagging_v1_integration_test.go
- globaltaggingv1/global_tagging_v1_suite_test.go
- globaltaggingv1/global_tagging_v1_test.go
This PR updates the Global Tagging service after recent API changes.
> fix(Global Tagging): update service after recent API changes

- casemanagementv1/case_management_v1.go
- casemanagementv1/case_management_v1_integration_test.go
- casemanagementv1/case_management_v1_test.go
- go.mod
- go.sum
This PR updates the case management int test to remove PII.
> test(Case Management): remove PII from integration test

- .gitignore
- .travis.yml
- Makefile
- README.md
- build/publishCodeCoverage.sh
This PR adds code coverage reporting to the project.
> build: add code coverage reporting to project

- globalcatalogv1/global_catalog_v1.go
- globalcatalogv1/global_catalog_v1_examples_test.go
- globalcatalogv1/global_catalog_v1_integration_test.go
- globalcatalogv1/global_catalog_v1_suite_test.go
- globalcatalogv1/global_catalog_v1_test.go
- go.mod
This PR contains a regen of the Global Catalog service and adds working examples
> fix(Global Catalog): regen service and add working examples

- atrackerv1/atracker_v1.go
- atrackerv1/atracker_v1_examples_test.go
- atrackerv1/atracker_v1_integration_test.go
- atrackerv1/atracker_v1_suite_test.go
- atrackerv1/atracker_v1_test.go
This PR contains a re-gen of the Activity Tracker service and some minor tweaks to the examples and int tests
> fix(Activity Tracker): re-gen service

- catalogmanagementv1/catalog_management_v1.go
- catalogmanagementv1/catalog_management_v1_integration_test.go
- catalogmanagementv1/catalog_management_v1_test.go
Updates the Catalog Management service after an API change in the delete_version_instance operation.
> fix(Catalog Management): re-gen after update to delete_version_instance

- catalogmanagementv1/catalog_management_v1.go
- catalogmanagementv1/catalog_management_v1_integration_test.go
- catalogmanagementv1/catalog_management_v1_old_integration_test.go
- catalogmanagementv1/catalog_management_v1_test.go
This PR contains a re-gen of the Catalog Management service after changes to some operation names.
> fix(Catalog Management): re-gen after operation name changes

- resourcecontrollerv2/resource_controller_v2.go
- resourcecontrollerv2/resource_controller_v2_examples_test.go
- resourcecontrollerv2/resource_controller_v2_integration_test.go
- resourcecontrollerv2/resource_controller_v2_suite_test.go
- resourcecontrollerv2/resource_controller_v2_test.go
This PR contains a re-gen of the Resource Controller service and unit test code, along with updates to the integration tests and examples.
> fix(Resource Controller): update service after recent API changes

- .secrets.baseline
- iamidentityv1/iam_identity_v1.go
- iamidentityv1/iam_identity_v1_examples_test.go
- iamidentityv1/iam_identity_v1_integration_test.go
- iamidentityv1/iam_identity_v1_suite_test.go
- iamidentityv1/iam_identity_v1_test.go
This PR updates the IAM Identity service after recent API updates.
> fix(IAM Identity): update service after recent API changes

- resourcemanagerv2/resource_manager_v2.go
- resourcemanagerv2/resource_manager_v2_examples_test.go
- resourcemanagerv2/resource_manager_v2_integration_test.go
- resourcemanagerv2/resource_manager_v2_suite_test.go
- resourcemanagerv2/resource_manager_v2_test.go
This PR updates the Resource Manager service and also add examples.
> fix(Resource Manager): update service after recent API changes and generate examples

- globalsearchv2/global_search_v2.go
- globalsearchv2/global_search_v2_examples_test.go
- globalsearchv2/global_search_v2_integration_test.go
- globalsearchv2/global_search_v2_suite_test.go
- globalsearchv2/global_search_v2_test.go
This PR updates the Global Search service after recent API changes.
> fix(Global Search): update service after recent API changes 

- .secrets.baseline
- iamaccessgroupsv2/iam_access_groups_v2.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
> fix(iam access groups): update sdk after recent api changes

- .travis.yml
This PR updates the version of the golangci-lint package in the travis config to fix linter errors during travis builds.
> build: update golangci-lint version in travis config

- enterprisemanagementv1/enterprise_management_v1_examples_test.go
> fix(enterprise management): add examples

- enterprisemanagementv1/enterprise_management_v1.go
- enterprisemanagementv1/enterprise_management_v1_suite_test.go
- enterprisemanagementv1/enterprise_management_v1_test.go
Re-gen of service after API changes.
> fix(Enterprise Management): update service after API changes

- enterprisemanagementv1/enterprise_management_v1_integration_test.go
This PR updates the Enterprise Manager SDK integration tests. Now the tests follow the pattern implemented in the Java, Node and Python SDKs.
> fix(enterprise management): fix integration tests

- atrackerv1/atracker_v1_examples_test.go
- casemanagementv1/case_management_v1_examples_test.go
- configurationgovernancev1/configuration_governance_v1_examples_test.go
- enterprisebillingunitsv1/enterprise_billing_units_v1_examples_test.go
- enterpriseusagereportsv1/enterprise_usage_reports_v1_examples_test.go
- globalcatalogv1/global_catalog_v1_examples_test.go
- globalsearchv2/global_search_v2_examples_test.go
- globaltaggingv1/global_tagging_v1_examples_test.go
- iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
- iamidentityv1/iam_identity_v1_examples_test.go
- iampolicymanagementv1/iam_policy_management_v1_examples_test.go
- openservicebrokerv1/open_service_broker_v1_examples_test.go
- posturemanagementv1/posture_management_v1_examples_test.go
- resourcemanagerv2/resource_manager_v2_examples_test.go
- usagemeteringv4/usage_metering_v4_examples_test.go
- usagereportsv4/usage_reports_v4_examples_test.go
- usermanagementv1/user_management_v1_examples_test.go
> Fix example labels

- go.mod
- go.sum
This PR upgrades the Go core to v5.4.2
> chore: upgrade go core to v5.4.2

- catalogmanagementv1/catalog_management_v1.go
- catalogmanagementv1/catalog_management_v1_integration_test.go
- catalogmanagementv1/catalog_management_v1_test.go
Fix tests for offering instances, including some new fields that are required as we move our offering instances onto resource controller.
Fixing tests and adding support for resource group and schematics workspace fields
> Catalog management offering instance fixes

- catalogmanagementv1/catalog_management_v1.go
- catalogmanagementv1/catalog_management_v1_integration_test.go
Add capability to provide a channel and install plan to offering instances
Adding new options (optional)
> feat: add channel and install plan to cat-mgmt offering instance

- globalsearchv2/global_search_v2.go
- globalsearchv2/global_search_v2_suite_test.go
- globalsearchv2/global_search_v2_test.go
- globaltaggingv1/global_tagging_v1.go
- globaltaggingv1/global_tagging_v1_suite_test.go
- globaltaggingv1/global_tagging_v1_test.go
These changes are made for regenerate GhoST services with latest APIs definitions
We have modified search ang tagging APIs
> Regen ghost

- iamidentityv1/iam_identity_v1.go
- iamidentityv1/iam_identity_v1_test.go
> fix(IAM Identity): re-gen service after recent API changes

- go.mod
- go.sum
This PR upgrades our go core dependency to version 5.5.1
> build: upgrade go core to version 5.5.1

- iamaccessgroupsv2/iam_access_groups_v2.go
- iamaccessgroupsv2/iam_access_groups_v2_suite_test.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
> fix(IAM Access Groups): update service after recent api changes

- README.md
- ibmcloudshellv1/ibm_cloud_shell_v1.go
- ibmcloudshellv1/ibm_cloud_shell_v1_examples_test.go
- ibmcloudshellv1/ibm_cloud_shell_v1_integration_test.go
- ibmcloudshellv1/ibm_cloud_shell_v1_suite_test.go
- ibmcloudshellv1/ibm_cloud_shell_v1_test.go
> feat(Cloudshell): add service, tests and examples to project

- .travis.yml
- README.md
- go.mod
> fix: upgrade min version to 1.14

- usagereportsv4/usage_reports_v4.go
- usagereportsv4/usage_reports_v4_suite_test.go
- usagereportsv4/usage_reports_v4_test.go
add optional name parameters to data type
Names will now show up when the optional parameter _names is passed
```
•••••••••••••••••••••••••••••••••••••••••••
Ran 65 of 65 Specs in 12.685 seconds
SUCCESS! -- 65 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
ok  	github.com/IBM/platform-services-go-sdk/usagereportsv4	12.953s
```
> fix(Usage Reports): add optional name parameters to struct

- README.md
> docs: add atracker service sdk reference url

- README.md
Activity Tracker is in GA now and  which includes a public documentation for it. This PR updates the reference link.
> doc: update atracker public doc link

- .travis.yml
- Makefile
This PR adds a security scan ([gosec](https://github.com/securego/gosec)) to the Travis CI pipeline and updates the golangci-lint version.
> build: add gosec scan to Travis

- .travis.yml
This PR updates the travis build script to add builds using go 1.16 and 1.17 (in addition to go 1.14, which is currently our minimum level of go supported by the project).
> build: build on go versions 1.16 and 1.17

- .travis.yml
Use go version 1.14.x for the deploy stage.
> build: use correct go version for deployment

- iamidentityv1/iam_identity_v1_examples_test.go
> docs: fix documentation

- iamidentityv1/iam_identity_v1.go
- iamidentityv1/iam_identity_v1_examples_test.go
- iamidentityv1/iam_identity_v1_integration_test.go
- iamidentityv1/iam_identity_v1_test.go
> feat(iam-identity): fixing examples

- ibmcloudshellv1/ibm_cloud_shell_v1_integration_test.go
This PR simply adds debug logging to the cloudshell integration test to aid in debugging.
> test(Cloud Shell): add debug logging to int test

- .cra/.cveignore
- .secrets.baseline
This PR adds a .cveignore file to ignore the packr/v2 snyk vulnerability until a fix can be put in place.
> chore: add .cveignore

- catalogmanagementv1/catalog_management_v1.go
- catalogmanagementv1/catalog_management_v1_integration_new_test.go
- catalogmanagementv1/catalog_management_v1_test.go
Re-generated the Catalog Management SDK code to contain the new PATCH operation for offerings.
Add support for PATCH offerings.
> fix(Catalog Management): update service to add patch operation

- .secrets.baseline
- go.mod
- go.sum
This PR updates the Go core version in the project.
> fix: bump go core to 5.9.3

- .travis.yml
- go.mod
- go.sum
This PR adds Go 1.18 to the Travis build.
> build: add go 1.18

- iamidentityv1/iam_identity_v1.go
- iamidentityv1/iam_identity_v1_examples_test.go
- iamidentityv1/iam_identity_v1_integration_test.go
> test(IAM Identity): update examples with right tags

- iamidentityv1/iam_identity_v1.go
- iamidentityv1/iam_identity_v1_test.go
The report schema is slightly improvised, incorporating the changes into SDKs
> fix(IAM Identity): update report schema and fix ITs

- atrackerv1/atracker_v1.go
- atrackerv1/atracker_v1_test.go
IBM Contact: van.bui@ibm.com
- Added in the new regions for eu-de and au-syd to the sdk
> fix(Activity Tracker): re-gen service after adding new region (eu-de and au-syd)

- contextbasedrestrictionsv1/context_based_restrictions_v1.go
- contextbasedrestrictionsv1/context_based_restrictions_v1_examples_test.go
- contextbasedrestrictionsv1/context_based_restrictions_v1_integration_test.go
- contextbasedrestrictionsv1/context_based_restrictions_v1_test.go
Add ability to query by rule enforcement modes (previously released) and add features needed for Context-based Restrictions rule API types.
- feat(Context-based Restrictions): add enforcement_mode query param
- feat(Context-based Restrictions): add service ref address location support
- feat(Context-based Restrictions): add rule API type support
> add latest Context-based Restrictions features

- atrackerv2/atracker_v2.go
- atrackerv2/atracker_v2_examples_test.go
- atrackerv2/atracker_v2_integration_test.go
- atrackerv2/atracker_v2_test.go
Signed-off-by: yingwang_us [bluewang@yahoo.com](mailto:bluewang@yahoo.com)
> Regen atracker 07152022

- atrackerv2/atracker_v2_integration_test.go
Signed-off-by: Ying Wang <yingwang@us.ibm.com>
rename potential offensive test ids for atracker integration tests
> fix(Activity Tracker): re-gen service after recent API changes

- contextbasedrestrictionsv1/context_based_restrictions_v1_examples_test.go
Signed-off-by: Stephen SooHoo <soohoos@us.ibm.com>
Better SDK example alignment with curl examples.
> refactor(Context-based Restrictions): update create zone examples

- .travis.yml
This commit enables building the project on Go 1.19.
It also updates the `golangci-lint` package version
to resolve a compatibility issue with the latest Go version.
Signed-off-by: Norbert Biczo <pyrooka@users.noreply.github.com>
> build: add Go 1.19

- .secrets.baseline
- iamaccessgroupsv2/iam_access_groups_v2.go
- iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
- iamaccessgroupsv2/iam_access_groups_v2_integration_test.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
This commit contains a re-gen of the service to
leverage the new Pagers emitted by the SDK generator.
> fix(IAM Access Groups): regen service to get Pagers

- atrackerv2/atracker_v2.go
- atrackerv2/atracker_v2_integration_test.go
- atrackerv2/atracker_v2_test.go
Signed-off-by: Veena Rao <veenar@us.ibm.com>
> fix(Activity Tracker): Changed password field name to api_key

- .secrets.baseline
- resourcecontrollerv2/resource_controller_v2.go
- resourcecontrollerv2/resource_controller_v2_examples_test.go
- resourcecontrollerv2/resource_controller_v2_integration_test.go
- resourcecontrollerv2/resource_controller_v2_test.go
This commit contains a re-gen of the Resource Controller service to leverage the new Pagers emitted by
the SDK generator.
> fix(Resource Controller): re-gen service to get new Pagers

- .secrets.baseline
- enterprisemanagementv1/enterprise_management_v1.go
- enterprisemanagementv1/enterprise_management_v1_examples_test.go
- enterprisemanagementv1/enterprise_management_v1_integration_test.go
- enterprisemanagementv1/enterprise_management_v1_test.go
This commit contains a re-gen of the Enterprise Management service to leverage the new Pagers emitted by the SDK generator.
> fix(Enterprise Management): re-gen service to get new Pagers

- .secrets.baseline
- usermanagementv1/user_management_v1.go
- usermanagementv1/user_management_v1_examples_test.go
- usermanagementv1/user_management_v1_integration_test.go
- usermanagementv1/user_management_v1_test.go
This commit contains a re-gen of the User Management service to leverage the new Pagers emitted by the SDK generator.
> fix(User Management): re-gen service to get new Pagers

- atrackerv2/atracker_v2.go
- atrackerv2/atracker_v2_examples_test.go
- atrackerv2/atracker_v2_integration_test.go
- atrackerv2/atracker_v2_test.go
> fix(Activity Tracker v2): add message field Settings struct

- iampolicymanagementv1/iam_policy_management_v1.go
- iampolicymanagementv1/iam_policy_management_v1_examples_test.go
- iampolicymanagementv1/iam_policy_management_v1_integration_test.go
- iampolicymanagementv1/iam_policy_management_v1_suite_test.go
- iampolicymanagementv1/iam_policy_management_v1_test.go
Updated time-based condition example and pattern, update property names based on API definition changes, and add support for tags
Issue: https://github.ibm.com/IAM/AM-issues/issues/1079
Based on API handbook, operation IDs were updated and this effected type and struct names of existing code (e.g., UpdateRole --> ReplaceRole, since it is a post operation).
> fix(IAM Policy Management): v2/policies updates for time-based condition and tags

- iampolicymanagementv1/iam_policy_management_v1.go
- iampolicymanagementv1/iam_policy_management_v1_examples_test.go
- iampolicymanagementv1/iam_policy_management_v1_integration_test.go
- iampolicymanagementv1/iam_policy_management_v1_test.go
Add format query parameter to GET by ID for v2 policy. This is needed for terraform provider changes. 
Previously missing GET by id query parameter "format", now that has been added for v2/policies. Also minor update to put go sdk in sync with API definition.
> fix(IAM Policy Management): Add format query parameter to GET by ID

- iamidentityv1/iam_identity_v1.go
- iamidentityv1/iam_identity_v1_examples_test.go
- iamidentityv1/iam_identity_v1_integration_test.go
- iamidentityv1/iam_identity_v1_suite_test.go
- iamidentityv1/iam_identity_v1_test.go
Go SDK doc for IAM identity. PR includes changes related
Create mfa report
Get mfa report
Get mfa user status
Change token expiration max and default value to 259200
> fix(IAM Identity): re-gen with latest API definition

- globalsearchv2/global_search_v2.go
- globalsearchv2/global_search_v2_test.go
removed an internal search parameter: is_hidden
> fix(Global Search): remove is_hidden param from search operation

- catalogmanagementv1/catalog_management_v1.go
- catalogmanagementv1/catalog_management_v1_integration_test.go
- catalogmanagementv1/catalog_management_v1_test.go
Regen Go SDK for Catalog Management service after recent API changes. These are needed by our terraform provider.
> feat(Catalog Management): re-gen service after recent API changes

- globalcatalogv1/global_catalog_v1.go
- globalcatalogv1/global_catalog_v1_integration_test.go
- globalcatalogv1/global_catalog_v1_suite_test.go
- globalcatalogv1/global_catalog_v1_test.go
Regen Go SDK for Catalog Management service after recent API changes. These are needed by our terraform provider.
> feat(Global Catalog): re-gen service after recent API changes

- enterprisemanagementv1/enterprise_management_v1.go
- enterprisemanagementv1/enterprise_management_v1_test.go
Schema change of traits field in create account request
> fix(Enterprise Management): re-gen service after updating trait schema

- enterprisemanagementv1/enterprise_management_v1.go
- enterprisemanagementv1/enterprise_management_v1_test.go
re-gen service after adding enterprise_iam_managed field in traits object
> feat(Enterprise Management): re-gen service after adding enterprise_iam_managed in traits

- iamaccessgroupsv2/iam_access_groups_v2.go
- iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
- iamaccessgroupsv2/iam_access_groups_v2_integration_test.go
- iamaccessgroupsv2/iam_access_groups_v2_suite_test.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
SDK adopters will be able to call access group template and assignment APIs.
API Definition
[Stage](https://test.cloud.ibm.com/docs/access-groups)
[Production](https://cloud.ibm.com/docs/access-groups)
**Tests**:
**Example Tests**:
**Integration Tests**:
> feat (IAM Access Groups): Add support for access group templates

- .travis.yml
- README.md
- go.mod
> feat: bump Go versions

- CHANGELOG.md
- resourcecontrollerv2/resource_controller_v2.go
- resourcecontrollerv2/resource_controller_v2_examples_test.go
- resourcecontrollerv2/resource_controller_v2_test.go
To support resource group filter for list reclamations API
A new filter called resource_group_id is added to the list reclamations API
> feat(Resource Controller): Support resource group filter for list reclamations

- iamaccessgroupsv2/iam_access_groups_v2.go
- iamaccessgroupsv2/iam_access_groups_v2_examples_test.go
- iamaccessgroupsv2/iam_access_groups_v2_integration_test.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
Removed "update" field from create template & template version request body.
> fix(IAM Access Groups): Remove update action control from assertions

- metricsrouterv3/metrics_router_v3.go
- metricsrouterv3/metrics_router_v3_test.go
Added new region Madrid(eu-es) to metrics-router
Added new region. No change in old code
> fix(Metrics Router): add new region eu-es

- usagereportsv4/usage_reports_v4.go
- usagereportsv4/usage_reports_v4_test.go
Add new query parameters to support pagination of API: /v1/billing-reports-snapshots
> feat(Usage Reports): Update query param for getting reports snapshot list

- .travis.yml
Bumps the linter version to the latest available (1.55.2).
> build: bump golangci-lint to 1.55.2

- atrackerv2/atracker_v2.go
- atrackerv2/atracker_v2_suite_test.go
- atrackerv2/atracker_v2_test.go
Added new region BNPP(eu-fr2) to ATracker
Added new region. No change in the old code
> fix(ATracker): add new region eu-fr2

- metricsrouterv3/metrics_router_v3.go
- metricsrouterv3/metrics_router_v3_examples_test.go
- metricsrouterv3/metrics_router_v3_integration_test.go
- metricsrouterv3/metrics_router_v3_suite_test.go
- metricsrouterv3/metrics_router_v3_test.go
Added new region BNPP(eu-fr2) to metrics-router
Added new region. No change in old code
> fix(Metrics Router): add new region eu-fr2

- iampolicymanagementv1/iam_policy_management_v1.go
- iampolicymanagementv1/iam_policy_management_v1_integration_test.go
- iampolicymanagementv1/iam_policy_management_v1_test.go
Issue: https://github.ibm.com/IAM/AM-issues/issues/2140
Minor fix of subject attribute value type to match API and other attributes value type.
Subject attribute value should not be limited to a string, but should allow for other types based on API. This change allows that.
Out of testing:
Integration tests:
```sh
shaunsmacibm@Shauns-MacBook-Pro iampolicymanagementv1 % go test -tags=integration
Running Suite: IamPolicyManagementV1 Suite
==========================================
Random Seed: 1705526859
Will run 212 of 212 specs
••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••••• …
```
> fix(IAM Policy Management): update subject attribute value

- globalsearchv2/global_search_v2.go
- globalsearchv2/global_search_v2_suite_test.go
- globalsearchv2/global_search_v2_test.go
- globaltaggingv1/global_tagging_v1.go
- globaltaggingv1/global_tagging_v1_suite_test.go
- globaltaggingv1/global_tagging_v1_test.go
New documentation about replace on get-tags swagger
> fix(Global Search/Tagging): re-gen services with latest API definition

- catalogmanagementv1/catalog_management_v1.go
- catalogmanagementv1/catalog_management_v1_examples_test.go
- catalogmanagementv1/catalog_management_v1_integration_test.go
- catalogmanagementv1/catalog_management_v1_test.go
Adding some fields that were missing from the api definition, removing a long deprecated `syndication` field from catalogs.
Supporting more API parameters
> feat(Catalog Management): add missed fields from api definition, remove old Syndication fields

- enterprisemanagementv1/enterprise_management_v1.go
- enterprisemanagementv1/enterprise_management_v1_integration_test.go
- enterprisemanagementv1/enterprise_management_v1_suite_test.go
- enterprisemanagementv1/enterprise_management_v1_test.go
added options field in create child account in enterprise payload.
> fix(Enterprise Management): add options property to create_account payload

- .secrets.baseline
- iamidentityv1/iam_identity_v1.go
- iamidentityv1/iam_identity_v1_examples_test.go
- iamidentityv1/iam_identity_v1_integration_test.go
- iamidentityv1/iam_identity_v1_suite_test.go
- iamidentityv1/iam_identity_v1_test.go
two new endpoints for apikey: Disable apikey and Enable apikey
> feat(IAM Identity): add disable_api_key and enable_api_key operations

- globalsearchv2/global_search_v2.go
- globalsearchv2/global_search_v2_test.go
Updated documentation about project onboarding
> fix(Global Search): add support for is_project_resource query param

- globaltaggingv1/global_tagging_v1.go
- globaltaggingv1/global_tagging_v1_test.go
> fix(Global Tagging): add 'update' option to attach_tag operation

- contextbasedrestrictionsv1/context_based_restrictions_v1.go
- contextbasedrestrictionsv1/context_based_restrictions_v1_integration_test.go
- contextbasedrestrictionsv1/context_based_restrictions_v1_test.go
- add "id" property to zone addresses (for use by terraform only)
- fix integration test to use valid location
- support address id property for terraform
> fix(Context-Based Restrictions): address ID support

- resourcecontrollerv2/resource_controller_v2.go
- resourcecontrollerv2/resource_controller_v2_examples_test.go
- resourcecontrollerv2/resource_controller_v2_integration_test.go
- resourcecontrollerv2/resource_controller_v2_test.go
> feat(Resource Controller): add "onetime_credentials" property in ResourceInstance and ResourceKey schemas

- .secrets.baseline
- partnercentersellv1/partner_center_sell_v1.go
- partnercentersellv1/partner_center_sell_v1_examples_test.go
- partnercentersellv1/partner_center_sell_v1_integration_test.go
- partnercentersellv1/partner_center_sell_v1_suite_test.go
- partnercentersellv1/partner_center_sell_v1_test.go
We are adding a new service that we plan to bring to the terraform provider
We are adding a new service that we plan to bring to the terraform provider
> feat(partner center sell): add partner-center-sell service to project

- README.md
> docs(README.md): add service table entry for Partner Center Sell service

- resourcecontrollerv2/resource_controller_v2.go
> feat(Resource Controller): deprecate alias, bindings APIs, and related schema items

- .secrets.baseline
- catalogmanagementv1/catalog_management_v1_integration_test.go
- partnercentersellv1/partner_center_sell_v1.go
- partnercentersellv1/partner_center_sell_v1_examples_test.go
- partnercentersellv1/partner_center_sell_v1_integration_test.go
- partnercentersellv1/partner_center_sell_v1_test.go
> fix(Partner Center Sell): re-gen service after recent API definition changes

- iamaccessgroupsv2/iam_access_groups_v2.go
- iamaccessgroupsv2/iam_access_groups_v2_suite_test.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
Added the support for error toolchain
> fix(IAM Access Groups): enable error toolchain

- iamaccessgroupsv2/iam_access_groups_v2.go
- iamaccessgroupsv2/iam_access_groups_v2_suite_test.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
**Tests:**
**Example Tests:**
**Integration Tests:**
> feat(IAM Access Groups): Add CRN filter

- iamaccessgroupsv2/iam_access_groups_v2.go
- iamaccessgroupsv2/iam_access_groups_v2_test.go
> feat(IAM Access Groups): Add CRN to schema

- partnercentersellv1/partner_center_sell_v1.go
- partnercentersellv1/partner_center_sell_v1_examples_test.go
- partnercentersellv1/partner_center_sell_v1_test.go
For deployments and plans tags should not be required
> feat(partner center sell): make tags on deployment creation optional

- partnercentersellv1/partner_center_sell_v1.go
- partnercentersellv1/partner_center_sell_v1_test.go
>   fix(Partner Center Sell): relax restrictions on catalog product media item fields
